name: Build

on:
  pull_request_review:
    types: [submitted]
    inputs:
      ci:
        description: "CI pipeline name"
        required: false
        default: "PR_Validation.yml"

  workflow_dispatch:
    inputs:
      ci:
        description: "CI pipeline name"
        required: false
        default: "PR_Validation.yml"

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check PR Valid
        run: |
          output=$(curl -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "branch=${{ github.ref }}" -d "event=pull_request" https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.event.inputs.ci }}/runs | jq -r '.workflow_runs[0] | "\(.conclusion)"')
          echo "::set-output name=status::$output"
        id: check

      - name: Abort if CI not successful
        if: steps.check.outputs.status != 'success'
        run: |
          echo ${{ steps.check.outputs.status }}
          exit 1

      - name: Abort if CI not successful
        if: steps.check.outputs.status == 'success'
        run: |
          echo "Running build steps..."
          exit 0